<a href="https://colab.research.google.com/github/inesarruda/Atividades-ML-Senac/blob/main/Atividade_de_Casa%2C_aula_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [ ]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr2 = np.arange(10, 20)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
arr3 = np.arange(10, 20, 2)
arr3

array([10, 12, 14, 16, 18])

In [ ]:
arr4 = np.arange(10, 20, 1.4)
arr4

array([10. , 11.4, 12.8, 14.2, 15.6, 17. , 18.4, 19.8])

In [ ]:
arr5 = np.linspace(10, 20, 11)
arr5

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [ ]:
arr6 = np.linspace(10, 20,101) #imprime 101 elementos igualmente espaçados entre 10 e 20
arr6

array([10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ,
       11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. , 12.1,
       12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1, 13.2,
       13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3, 15.4,
       15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4, 16.5,
       16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5, 17.6,
       17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7,
       18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8,
       19.9, 20. ])

In [ ]:
arr7 = np.linspace(0, np.pi, 100)
arr7

array([0.        , 0.03173326, 0.06346652, 0.09519978, 0.12693304,
       0.1586663 , 0.19039955, 0.22213281, 0.25386607, 0.28559933,
       0.31733259, 0.34906585, 0.38079911, 0.41253237, 0.44426563,
       0.47599889, 0.50773215, 0.53946541, 0.57119866, 0.60293192,
       0.63466518, 0.66639844, 0.6981317 , 0.72986496, 0.76159822,
       0.79333148, 0.82506474, 0.856798  , 0.88853126, 0.92026451,
       0.95199777, 0.98373103, 1.01546429, 1.04719755, 1.07893081,
       1.11066407, 1.14239733, 1.17413059, 1.20586385, 1.23759711,
       1.26933037, 1.30106362, 1.33279688, 1.36453014, 1.3962634 ,
       1.42799666, 1.45972992, 1.49146318, 1.52319644, 1.5549297 ,
       1.58666296, 1.61839622, 1.65012947, 1.68186273, 1.71359599,
       1.74532925, 1.77706251, 1.80879577, 1.84052903, 1.87226229,
       1.90399555, 1.93572881, 1.96746207, 1.99919533, 2.03092858,
       2.06266184, 2.0943951 , 2.12612836, 2.15786162, 2.18959488,
       2.22132814, 2.2530614 , 2.28479466, 2.31652792, 2.34826

In [ ]:
minhaMatriz = np.array([[1,2,3],
[4,5,6]])

In [ ]:
minhaMatriz = np.array([[1,2,3], [4,5,6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
minhaLista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [ ]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [ ]:
x = np.zeros(3) #vetor
x

array([0., 0., 0.])

In [ ]:
x = np.zeros((3,2)) #matriz 3x2 de zeros
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
print(np.zeros(3))

[0. 0. 0.]


In [ ]:
print(np.zeros((3, 2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
x = np.ones((5,3)) #matriz 5x3 onde todos os elementos são 1
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

Desafio: como obter uma matriz 4x4 apenas com
números 8?

In [ ]:
m=4 #dimensão de linhas
n=4 #dimensão de colunas
m8 = np.zeros((m, n))
for i in range(m):
  for j in range(n):
    if m8[i][j] == 0:
      m8[i][j] = 8
print(m8)


[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]


In [ ]:
z= np.diag(np.array([1, 2, 3, 4, 5, 6])) #Transforma a matriz em uma matriz diagonal com dimensão len(z)
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
y = np.eye(5) #matriz unitária de dimensão 5 com float
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
y = np.eye(5, dtype= int) #matriz unitária de dimensão 5 com int
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.shape(minhaMatriz)

(3, 3)

In [ ]:
minhaMatriz.shape

(3, 3)

In [ ]:
type(minhaMatriz) #Verifica o tipo da matriz

numpy.matrix

In [ ]:
minhaMatriz.dtype #Verifica o tipo dos dados da matriz

dtype('int64')

In [ ]:
minhaMatriz[2,1] #Acessa o elemento na linha 2, coluna 1, lembrando que o índice começa em 0

48

In [ ]:
print(minhaMatriz[0,:]) #printa a primeira linha da matriz

[[13 81 22]]


In [ ]:
print(minhaMatriz[:,2]) #printa a terceira coluna da matriz. 

[[22]
 [59]
 [94]]


In [ ]:
minhaMatriz[1,0] = 100 #Altera o elemento da segunda linha e primeira coluna para 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [9]:
meuArray =np.array([1,2,3,4,5,6,7,8,9,10])

In [10]:
np.sum(meuArray) #Obtendo a soma dos valores do array:

55

In [11]:
np.prod(meuArray) #Obtendo o produto:

3628800

In [12]:
np.cumsum(meuArray) #Obtendo a soma acumulada

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [13]:
meuArray.min() #Obtendo o valor mínimo do array:

1

In [15]:
meuArray.max() #Obtendo o valor máximo do array:

10

In [16]:
np.mean(meuArray) #Obtendo a média dos valores do array:

5.5

In [17]:
np.median(meuArray) #Obtendo a mediana:

5.5

In [18]:
np.var(meuArray) #Obtendo a variância dos valores:

8.25

In [19]:
np.std(meuArray) #Obtendo o desvio padrão dos valores:

2.8722813232690143

Desafio\
Criar um array unidimensional usando arange com 20 elementos;\
● “Varrer” o array para obter os pares;\
● “Varrer” o array para obter os ímpares;\
● Obter a média, a soma, o produto, a variância e o desvio padrão
do array.\
● Saber se os valores são maiores que 5;\
● Obter os valores maiores que 5.

In [28]:
novo_array = np.arange(1,21)
print(f'O novo_array é {novo_array}')
novo_array_par = []
novo_array_imp = []
mult = 1
for i in novo_array:
  mult = mult*i
  if i %2 != 0:
    novo_array_imp.append(i) 
  else:
    novo_array_par.append(i) 
print(f'Os valores pares foram: {novo_array_par}')
print(f'Os valores impares foram: {novo_array_imp}')
print(f'A média de novo_array é: {np.mean(novo_array)}')
print(f'A soma de novo_array é: {np.sum(novo_array)}')
print(f'A multiplicação dos elementos de novo_array é: {mult}')
print(f'A variância dos elementos de novo_array é: {np.var(novo_array)}')
print(f'O desvio padrão dos elementos de novo_array é: {np.std(novo_array)}')


O novo_array é [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Os valores pares foram: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
Os valores impares foram: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
A média de novo_array é: 10.5
A soma de novo_array é: 210
A multiplicação dos elementos de novo_array é: 2432902008176640000
A variância dos elementos de novo_array é: 33.25
O desvio padrão dos elementos de novo_array é: 5.766281297335398
